CREATE TABLE Paises( siglas VARCHAR(2) NOT NUll, pais VARCHAR(64), continente VARCHAR(37), PRIMARY KEY(siglas)) ENGINE=InnoDB;
INSERT INTO Paises(siglas, pais, continente) VALUES ("AD", "Andorra", "Europa"), ("AE", "Emiratos Arabes Unidos", "Asia"), ("AF", "Afganistan", "Asia"),
("AG", "Antigua y Barbuda", "América del Norte"), ("AI", "Anguilla", "América del Norte"), ("AL", "Albania", "Europa"), ("AM", "Armenia", "Asia"),
("AO", "Angola", "África"), ("AQ", "Antartida", "Antártica"), ("AR", "Argentina", "América del Sur"), ("AS", "Samoa Americana", "Oceanía"),
("AT", "Austria", "Europa"), ("AU", "Australia", "Oceanía"), ("AW", "Aruba", "América del Norte"), ("AX", "Åland", "Europa"), ("AZ", "Azerbaiyan", "Asia"),
("BA", "Bosnia-Herzegovina", "Europa"), ("BB", "Barbados", "América del Norte"), ("BD", "Banglades", "Asia"), ("BE", "Belgica", "Europa"), ("BF", "Burkina Faso", "África"),
("BG", "Bulgaria", "Europa"), ("BH", "Barein", "Asia"), ("BI", "Burundi", "África"), ("BJ", "Benin", "África"), ("BL", "San Bartolome", "América del Norte"),
("BM", "Bermudas", "América del Norte"), ("BN", "Brunei", "Asia"), ("BO", "Bolivia", "América del Sur"), ("BQ", "Isla de Bonaire", "América del Norte"),
("BR", "Brasil", "América del Sur"), ("BS", "Bahamas", "América del Norte"), ("BT", "Butan", "Asia"), ("BV", "Isla Bouvet", "Antárctica"), ("BW", "Botsuana", "África"),
("BY", "Bielorrusia", "Europa"), ("BZ", "Belice", "América del Norte"), ("CA", "Canada", "América del Norte"), ("CC", "Islas Cocos", "Asia"),
("CD", "República Democrática del Congo", "África"), ("CF", "Republica Centroafricana", "África"), ("CG", "Congo", "África"), ("CH", "Suiza", "Europa"),
("CI", "Costa de Marfil", "África"), ("CK", "Islas Cook", "Oceanía"), ("CL", "Chile", "América del Sur"), ("CM", "Camerun", "África"), ("CN", "China", "Asia"),
("CO", "Colombia", "América del Sur"), ("CR", "Costa Rica", "América del Norte"), ("CU", "Cuba", "América del Norte"), ("CV", "Cabo Verde", "África"), 
("CW", "Curazao", "América del Norte"), ("CX", "Isla de Navidad", "Asia"), ("CY", "Chipre", "Europa"), ("CZ", "Republica Checa", "Europa"), ("DE", "Alemania", "Europa"), 
("DJ", "Yibuti", "África"), ("DK", "Dinamarca", "Europa"), ("DM", "Dominica", "América del Norte"), ("DO", "Republica Dominicana", "América del Norte"), ("DZ", "Argelia", "África"), 
("EC", "Ecuador", "América del Sur"), ("EE", "Estonia", "Europa"), ("EG", "Egipto", "África"), ("EH", "Sahara Occidental", "África"), ("ER", "Eritrea", "África"), ("ES", "España", "Europa"), 
("ET", "Etiopia", "África"), ("FI", "Finlandia", "Europa"), ("FJ", "Fiyi", "Oceanía"), ("FK", "Islas Malvinas", "América del Sur"), ("FM", "Estados Federados de Micronesia", "Oceanía"), 
("FO", "Islas Feroe", "Europa"), ("FR", "Francia", "Europa"), ("GA", "Gabon", "África"), ("GB", "Reino Unido", "Europa"), ("GD", "Granada", "América del Norte"), ("GE", "Georgia", "Asia"), 
("GF", "Guayana Francesa", "América del Sur"), ("GG", "Guernsey", "Europa"), ("GH", "Ghana", "África"), ("GI", "Gibraltar", "Europa"), ("GL", "Groenlandia", "América del Norte"), 
("GM", "Gambia", "África"), ("GN", "Guinea", "África"), ("GP", "Guadalupe", "América del Norte"), ("GQ", "Guinea Ecuatorial", "África"), ("GR", "Grecia", "Europa"), 
("GS", "Islas Georgias del Sur y Sandwich del Sur", "Antárctica"), ("GT", "Guatemala", "América del Norte"), ("GU", "Guam", "Oceanía"), ("GW", "Guinea-Bisau", "África"), 
("GY", "Guyana", "América del Sur"), ("HK", "Hong Kong", "Asia"), ("HM", "Islas Heard y McDonald", "Antárctica"), ("HN", "Honduras", "América del Norte"), ("HR", "Croacia", "Europa"), 
("HT", "Haiti", "América del Norte"), ("HU", "Hungria", "Europa"), ("ID", "Indonesia", "Asia"), ("IE", "Irlanda", "Europa"), ("IL", "Israel", "Asia"), ("IM", "Isla de Man", "Europa"), 
("IN", "India", "Asia"), ("IO", "Territorio Británico del Océano Índico", "Asia"), ("IQ", "Iraq", "Asia"), ("IR", "Iran", "Asia"), ("IS", "Islandia", "Europa"), ("IT", "Italia", "Europa"), 
("JE", "Jersey", "Europa"), ("JM", "Jamaica", "América del Norte"), ("JO", "Jordania", "Asia"), ("JP", "Japon", "Asia"), ("KE", "Kenia", "África"), ("KG", "Kirguistan", "Asia"), ("KH", "Camboya", "Asia"), 
("KI", "Kiribati", "Oceanía"), ("KM", "Comoras", "África"), ("KN", "San Cristóbal y Nieves", "América del Norte"), ("KP", "Corea del Norte", "Asia"), ("KR", "Corea del Sur", "Asia"), ("KW", "Kuwait", "Asia"), 
("KY", "Islas Caiman", "América del Norte"), ("KZ", "Kazajistan", "Asia"), ("LA", "Laos", "Asia"), ("LB", "Libano", "Asia"), ("LC", "Santa Lucia", "América del Norte"), ("LI", "Liechtenstein", "Europa"), 
("LK", "Sri Lanka", "Asia"), ("LR", "Liberia", "África"), ("LS", "Lesoto", "África"), ("LT", "Lituania", "Europa"), ("LU", "Luxemburgo", "Europa"), ("LV", "Letonia", "Europa"), ("LY", "Libia", "África"), 
("MA", "Marruecos", "África"), ("MC", "Monaco", "Europa"), ("MD", "Moldavia", "Europa"), ("ME", "Montenegro", "Europa"), ("MF", "Isla de San Martín", "América del Norte"), ("MG", "Madagascar", "África"), 
("MH", "Islas Marshall", "Oceanía"), ("MK", "Macedonia del Norte", "Europa"), ("ML", "Mali", "África"), ("MM", "Birmania", "Asia"), ("MN", "Mongolia", "Asia"), ("MO", "Macao", "Asia"), 
("MP", "Islas Marianas del Norte", "Oceanía"), ("MQ", "Martinica", "América del Norte"), ("MR", "Mauritania", "África"), ("MS", "Montserrat", "América del Norte"), ("MT", "Malta", "Europa"), 
("MU", "Mauricio", "África"), ("MV", "Maldivas", "Asia"), ("MW", "Malaui", "África"), ("MX", "Mexico", "América del Norte"), ("MY", "Malasia", "Asia"), ("MZ", "Mozambique", "África"), 
("NA", "Namibia", "África"), ("NC", "Nueva Caledonia", "Oceanía"), ("NE", "Niger", "África"), ("NF", "Isla Norfolk", "Oceanía"), ("NG", "Nigeria", "África"), ("NI", "Nicaragua", "América del Norte"), 
("NL", "Holanda", "Europa"), ("NO", "Noruega", "Europa"), ("NP", "Nepal", "Asia"), ("NR", "Nauru", "Oceanía"), ("NU", "Niue", "Oceanía"), ("NZ", "Nueva Zelanda", "Oceanía"), ("OM", "Oman", "Asia"), 
("PA", "Panama", "América del Norte"), ("PE", "Peru", "América del Sur"), ("PF", "Polinesia Francesa", "Oceanía"), ("PG", "Papua Nueva Guinea", "Oceanía"), ("PH", "Filipinas", "Asia"), ("PK", "Pakistan", "Asia"), 
("PL", "Polonia", "Europa"), ("PM", "San Pedro y Miquelon", "América del Norte"), ("PN", "Islas Pitcairn", "Oceanía"), ("PR", "Puerto Rico", "América del Norte"), ("PS", "Palestina", "Asia"), ("PT", "Portugal", "Europa"), 
("PW", "Palaos", "Oceanía"), ("PY", "Paraguay", "América del Sur"), ("QA", "Qatar", "Asia"), ("RE", "Reunion", "África"), ("RO", "Rumania", "Europa"), ("RS", "Serbia", "Europa"), ("RU", "Rusia", "Europa"), 
("RW", "Ruanda", "África"), ("SA", "Arabia Saudita", "Asia"), ("SB", "Islas Salomón", "Oceanía"), ("SC", "Seychelles", "África"), ("SD", "Sudán", "África"), ("SE", "Suecia", "Europa"), ("SG", "Singapur", "Asia"), 
("SH", "Santa Elena, Ascensión y Tristán de Acuña", "África"), ("SI", "Eslovenia", "Europa"), ("SJ", "Svalbard y Jan Mayen", "Europa"), ("SK", "Eslovaquia", "Europa"), ("SL", "Sierra Leona", "África"), 
("SM", "San Marino", "Europa"), ("SN", "Senegal", "África"), ("SO", "Somalia", "África"), ("SR", "Surinam", "América del Sur"), ("SS", "Sudán del Sur", "África"), ("ST", "Santo Tome y Principe", "África"), 
("SV", "El Salvador", "América del Norte"), ("SX", "San Martín (Paises Bajos)", "América del Norte"), ("SY", "Siria", "Asia"), ("SZ", "Suazilandia", "África"), ("TC", "Islas Turcas y Caicos", "América del Norte"), 
("TD", "Chad", "África"), ("TF", "Tierras Australes y Antárticas Francesas", "Antárctica"), ("TG", "Togo", "África"), ("TH", "Tailandia", "Asia"), ("TJ", "Tayikistan", "Asia"), ("TK", "Tokelau", "Oceanía"), 
("TL", "Timor Oriental", "Oceanía"), ("TM", "Turkmenistan", "Asia"), ("TN", "Tunez", "África"), ("TO", "Tonga", "Oceanía"), ("TR", "Turquia", "Asia"), ("TT", "Trinidad y Tobago", "América del Norte"), 
("TV", "Tuvalu", "Oceanía"), ("TW", "Taiwan", "Asia"), ("TZ", "Tanzania", "África"), ("UA", "Ucrania", "Europa"), ("UG", "Uganda", "África"), ("UM", "Islas Ultramarinas Menores de Estados Unidos", "Oceanía"), 
("US", "Estados Unidos", "América del Norte"), ("UY", "Uruguay", "América del Sur"), ("UZ", "Uzbekistan", "Asia"), ("VA", "Ciudad del Vaticano", "Europa"), ("VC", "Kingstown", "América del Norte"), 
("VE", "Venezuela", "América del Sur"), ("VG", "Islas Vírgenes Británicas", "América del Norte"), ("VI", "Islas Vírgenes de los Estados Unidos", "América del Norte"), ("VN", "Vietnam", "Asia"), 
("VU", "Vanuatu", "Oceanía"), ("WF", "Wallis y Futuna", "Oceanía"), ("WS", "Samoa", "Oceanía"), ("XK", "Kosovo", "Europa"), ("YE", "Yemen", "Asia"), ("YT", "Mayotte", "África"), ("ZA", "Sudáfrica", "África"), 
("ZM", "Zambia", "África"), ("ZW", "Zimbabue", "África");

